const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '../static/app.js'), 'utf8');
const code = source.slice(source.indexOf('async function commitShotReorder('), source.indexOf('// Reorder through one pointer stream.'));
function setup() {
  const c = { state: { bundle: {project: {id:'p'}, shots: [1,2,3,4].map(id => ({id:String(id)}))}, tablePrefs:{}, changeVersion:0, dirty:false }, shotReorderInFlight:false, setTimeout, requests:[] };
  for (const name of ['toast','recordHistory','setSaveStatus','renderCurrentView','renderProjectHeader','selectShot','scheduleAutoSave','syncDerivedTimeline']) c[name] = () => {};
  c.adoptServerBundle = x => x;
  c.api = async (url, options) => { c.requests.push(options.json); return structuredClone(c.state.bundle); };
  c.saveProject = async () => { c.state.dirty = false; return true; };
  vm.createContext(c); vm.runInContext(code, c);
  return c;
}
const ids = c => Array.from(c.state.bundle.shots, s => s.id);
(async () => {
  let c = setup();
  assert.equal(await c.commitShotReorder('1','3',true), true);
  assert.deepEqual(ids(c), ['2','3','1','4']);
  assert.deepEqual(Array.from(c.requests[0].base_order), ['1','2','3','4']);
  assert.deepEqual(Array.from(c.state.bundle.shots, s => s.number), ['001','002','003','004']);
  assert.equal(await c.commitShotReorder('4','2',false), true);
  assert.deepEqual(ids(c), ['4','2','3','1']);
  c = setup();
  assert.equal(await c.commitShotReorder('1','4',true,{groupIds:['2','1']}), true);
  assert.deepEqual(ids(c), ['3','4','1','2']);
  assert.equal(c.requests.length, 1);
  c = setup();
  c.api = async () => { c.state.bundle.shots[0].title='new edit'; throw Error('offline'); };
  assert.equal(await c.commitShotReorder('1','4',true), false);
  assert.deepEqual(ids(c), ['1','2','3','4']);
  assert.equal(c.state.bundle.shots.find(s=>s.id==='2').title,'new edit');
  assert.equal(c.shotReorderInFlight, false);
  c = setup();
  c.api = async () => { const stale=structuredClone(c.state.bundle); c.state.changeVersion++; c.state.dirty=true; c.state.bundle.shots[0].title='during request'; return stale; };
  assert.equal(await c.commitShotReorder('1','4',true), true);
  assert.equal(c.state.bundle.shots[0].title,'during request');
  c = setup(); c.state.dirty=true;
  assert.equal(await c.commitShotReorder('1','4',true), true);
  assert.equal(c.state.dirty,false);
  console.log('PASS: single/group reorder, sequential numbering, repeated drag, failure rollback, concurrent edit, dirty-save flush');
})().catch(e => { console.error(e); process.exitCode=1; });
