/* Functional-only QA against a throwaway local server/database. No screenshots or production writes. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(root,'scratch','r33-qa-'));
const python=process.env.QA_PYTHON || 'C:/Users/Hatsune/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const base='http://127.0.0.1:18796';
const server=spawn(python,['-u','server.py'],{cwd:root,windowsHide:true,env:{...process.env,PORT:'18796',STORYBOARD_BIND:'127.0.0.1',STORYBOARD_DATA_ROOT:temp,STORYBOARD_ADMIN_USER:'qa-admin',STORYBOARD_ADMIN_PASSWORD:'Isolated-QA-2026!'}});
let logs='';server.stdout.on('data',d=>logs=(logs+d).slice(-6000));server.stderr.on('data',d=>logs=(logs+d).slice(-6000));
let browser;
(async()=>{
  for(let n=0;n<80;n++){try{if((await fetch(base+'/healthz')).ok)break;}catch(_){}await new Promise(r=>setTimeout(r,150));}
  const edge=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
  browser=await chromium.launch({headless:true,...(edge?{executablePath:edge}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
  page.setDefaultTimeout(10000);
  page.on('pageerror',e=>errors.push(e.message));
  const session=await (await page.request.post(base+'/api/login',{data:{username:'qa-admin',password:'Isolated-QA-2026!'}})).json();
  const bundle=await (await page.request.post(base+'/api/projects',{headers:{'X-CSRF-Token':session.csrf},data:{name:'R33 functional fixture'}})).json();
  await page.goto(base);await page.waitForFunction(()=>typeof state!=='undefined' && state.session);
  await page.evaluate(id=>openProject(id),bundle.project.id);
  await page.getByRole('button',{name:'灯光平面图',exact:true}).click();
  const canvas=page.locator('.ff-boards');await canvas.getByRole('button',{name:'新建画板',exact:true}).click();
  await canvas.getByRole('button',{name:'灯具',exact:true}).click();
  assert.equal(await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items.length),1);
  await canvas.getByLabel('灯具附件',{exact:true}).selectOption('grid');
  await page.waitForFunction(()=>creativeBoardsMount.getDraft().boards[0].items[0].attachment==='grid');
  assert.equal(await canvas.getByLabel('光束展开角（°）',{exact:true}).inputValue(),'40');
  const item=canvas.locator('.ff-boards-item').first(),box=await item.boundingBox();
  const oldX=await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].x);
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+40,{steps:8});await page.mouse.up();
  const newX=await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].x);assert.ok(newX>oldX,'pointer drag moves the model');
  await canvas.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].x),oldX);
  await canvas.getByRole('button',{name:'重做',exact:true}).click();assert.equal(await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].x),newX);
  const rotate=await canvas.locator('.ff-boards-rotate').boundingBox();
  const rotationBefore=await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].rotation);
  await page.mouse.move(rotate.x+11,rotate.y+11);await page.mouse.down();await page.keyboard.down('Shift');await page.mouse.move(rotate.x+90,rotate.y+70,{steps:8});await page.mouse.up();await page.keyboard.up('Shift');
  const rotationAfter=await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].rotation);
  assert.notEqual(rotationAfter,rotationBefore);assert.equal(rotationAfter%15,0,'rotation snaps to 15 degrees');
  await canvas.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await page.evaluate(()=>creativeBoardsMount.getDraft().boards[0].items[0].rotation),rotationBefore);
  assert.equal(await page.evaluate(()=>creativeBoardsMount.flush()),true);
  const saved=await (await page.request.get(`${base}/api/projects/${bundle.project.id}/creative-boards`)).json();
  assert.equal(saved.boards[0].items[0].x,newX);assert.equal(saved.boards[0].items[0].attachment,'grid');
  await page.getByRole('button',{name:'情绪板',exact:true}).click();await canvas.getByRole('button',{name:'新建画板',exact:true}).click();
  await canvas.getByRole('button',{name:'便签',exact:true}).click();assert.equal(await page.evaluate(()=>creativeBoardsMount.flush()),true);
  await page.getByRole('button',{name:'分镜工作台',exact:true}).click();
  await page.evaluate(()=>{void openRichShotEditor(state.bundle.shots[0],'description');});
  const editor=page.locator('.rich-editor-surface');await editor.fill('Styled storyboard text');
  await editor.press('Control+a');await editor.press('Control+b');
  await page.locator('.rich-editor-dialog form').evaluate(form=>form.requestSubmit());
  await page.waitForFunction(()=>state.bundle.shots[0].description==='Styled storyboard text');
  assert.equal(await page.evaluate(()=>state.bundle.shots[0].rich_text_json.description[0].bold),true);
  assert.equal(await page.evaluate(()=>saveProject(false)),true);
  const read=await (await page.request.get(`${base}/api/projects/${bundle.project.id}`)).json();assert.equal(read.shots[0].rich_text_json.description[0].bold,true);
  await page.locator('#sidebarCollapseBtn').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sidebar-collapsed')),true);
  await page.locator('#sidebarCollapseBtn').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sidebar-collapsed')),false);
  assert.deepEqual(errors,[]);
  console.log('PASS local app boot, sidebar navigation/collapse, canvas pointer drag, attachment switching, undo/redo, save/readback, moodboard and rich-text persistence');
})().catch(e=>{console.error(e);console.error(logs);process.exitCode=1;}).finally(async()=>{
  if(browser)await browser.close();server.kill();
  // Retain isolated fixture for debugging; never touch the application data directory.
  console.log('QA fixture:',temp);
});
