const assert = require('node:assert/strict');
const { dialogReturnTarget, restoreDialogFocus } = require('../dist/lib/dialog-focus.js');
let focused = 0;
const opener = { tagName: 'BUTTON', isConnected: true, closest: () => null, focus: options => { assert.equal(options.preventScroll, true); focused++; } };
const menuItem = { tagName: 'DIV', closest: () => ({ role: 'menu' }) };
assert.equal(dialogReturnTarget(opener, null), opener);
assert.equal(dialogReturnTarget(menuItem, opener), opener);
const close = new Event('close', { cancelable: true });
let callerInvoked = 0;
restoreDialogFocus(close, opener, () => { callerInvoked++; });
assert.equal(callerInvoked, 1);
assert.equal(focused, 1);
assert(close.defaultPrevented);
const customClose = new Event('close', { cancelable: true });
restoreDialogFocus(customClose, opener, event => event.preventDefault());
assert.equal(focused, 1);
const removedClose = new Event('close', { cancelable: true });
restoreDialogFocus(removedClose, { ...opener, isConnected: false });
assert.equal(focused, 1);
assert.equal(removedClose.defaultPrevented, false);
console.log('Dialog focus: opener, menu fallback, caller cancellation and removed opener passed');
